### ISSUE TITLE
TypeError in parsePlaceholders

### ISSUE THREAD

**Issue by kuon** [Durss/Twitchat#60]
There is an exception in `parsePlaceholders` if the `src` argument is null.

https://github.com/Durss/Twitchat/blob/26fd2ab854e4b5b1ded08fd9718bc764007cedac/src_front/utils/triggers/TriggerActionHandler.ts#L2430

It throws `TypeError: can't access property "toString", n is undefined`.

Also, in the above linked source, the `toString()` function is called twice in a row, I think the first call should be removed and a null check should be added.

I highly suggest to use an utility function like this instead of `Object.toString()`:

```
function toStr(obj) { // prevent name clash even if toString should be safe
    if (obj === undefined) return null; // clean handling of undefined and null
    if (obj === null) return null;
    return Object.prototype.toString.call(obj); // ensure it has not been overriden to avoid any obscure bug
}
```

**Comment by Durss** [comment]
Hello again :)

Can you tell me in which context you got this error?
I could indeed patch such kind of error by just checking if the parameter is filled, but there shouldn't be such error in the basis so I'd prefer to fix it at its root instead of patching it and potentially hidding other issues in the future.

**Comment by Durss** [comment]
Thanks! 
There was other trigger actions concerned with this issue that I've fixed in the meantime !
