### ISSUE TITLE
Idea: twitchat should retain connected tchats after refresh

### ISSUE THREAD

**Issue by Hezoq** [Durss/Twitchat#75]
it would be great to keep all configuration of multiple tchat connections after refresh

**Comment by Durss** [comment]
I hesitated saving these params.
It's not the first time this is brought up so I might make it so it automatically reconnects.

My point of view on this was that, as mods we might not want to reconnect to the same channel(s) everytime.
Also, we generally want to connect to a channel that we follow and that's live, that's why I show our live following by default when clicking on "+" to search for a channel.
I thought this solution was a nice half/half solution between connecting to offline/useless chans and connecting to the ones we need.

Something else that motivated this choice is the fact i'm limitting the number of chans we can connect to.
IIRC it's limitted to 5 for now. This is due to twitch API quotas that might be reached if we connect to more chans (i actually have to properly make the maths about this).
This means that if we moderate more than 5 chans, we may have to disconnect/reconnect chans anyways. Given that, i thought it was simpler to simply connect to the chans we want on-demand.

But as said before, it's not the first time i get "complains" about this so I might change that anyways :)

**Comment by Durss** [comment]
That's possible since a bit more than 2 weeks.
It's possible to pin channels so it automatically reconnects on app load.
